---
- name: Installing httpd 
  hosts: all
  become: yes

  tasks:
    - name: install appache server 
      shell:
       name: httpd 
       state: latest
    - name: starting service and making it boot persisstant 
      service: 
       status: started
       enabled: yes
    - name: checking status of httpd service 
      shell: systemctl status sshd
        name: httpd
        register: status_httpd 
    - name: result 
      debug:
       msg: "service is {{status_httpd.stdout}}"
        

    
